# Generated by Django 4.2.5 on 2024-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_business_user_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
